#日志配置，此处使用默认日志
logging:
 config: classpath:log4j2.xml
 level:
  org.springframework: WARN
  com.jees: DEBUG

spring:
 application:
  name: jees-jsts

jees:
 jsts:
  message:
   request:
    enable: true
    clazz: com.jees.interf.IRequest,com.jees.interf.IResponse
   handler:
    enable: true
    clazz: com.jees.interf.IResponse
   error:
    enable: true
    clazz: com.jees.interf.IError
  socket:
   enable: false
   lostTime: 0
   standTime: 60000
   port: 8000
  websocket:
   ssl:
    enable: true
    file: C:/Tomcat 9.0/cert/1683812_www.jeesupport.com.pfx
    keyfile: C:/Tomcat 9.0/cert/1683812_www.jeesupport.com.txt
    type: PKCS12
    pass: T2eyqsj2
   enable: true
   url: /
   lostTime: 0
   standTime: 60000
   port: 8001
  connector:
   enable: false
   retry:
    max: 3
    rate: 10000
    delay: 300000
   hosts: 127.0.0.1:8000

