#日志配置，此处使用默认日志
logging:
 config: classpath:log4j2.xml
 level:
  com:
   atomikos: WARN
   jees: DEBUG
  org:
   springframework: WARN

spring:
 application:
  name: jees-jdbs
# Redis数据库索引（默认为0）
 redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  pool:
# 连接池最大连接数（使用负值表示没有限制）
   max-active: 8
# 连接池最大阻塞等待时间（使用负值表示没有限制）
   max-wait: -1
# 连接池中的最大空闲连接
   max-idle: 8
# 连接池中的最小空闲连接
   min-idle: 0
# 连接超时时间（毫秒）
   timeout: 0
  package: com.jees.test.entity

jees:
 jdbs:
  enable: false
  defaultDB: testa
  dbNames: testa, testb
  trans:
   timeout: 3000
   allowCustomIsolationLevels: true
  config:
   testa:
    dbtype: mysql2
    orm: hibernate
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/testa
    pinGlobalTxToPhysicalConnection: true
    uniqueResourceName: datasourceA
    xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    poolSize: 1
    maxPoolSize: 3
    minPoolSize: 1
    maxIdleTime: 60
    packagesToScan: com.jees.test.entity
    hibernate:
     dialect: org.hibernate.dialect.MySQL55Dialect
     showSql: true
     factoryClass: org.hibernate.transaction.JTATransactionFactory
     hbm2ddl: create
     platform: com.jees.core.database.config.AtomikosJtaPlatform
     coordinatorClass: jta
   testb:
    dbtype: mysql
    orm: hibernate
    user: root
    password: root
    url: jdbc:mysql://localhost:3306/testb
    pinGlobalTxToPhysicalConnection: true
    uniqueResourceName: datasourceB
    xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    poolSize: 1
    maxPoolSize: 3
    minPoolSize: 1
    maxIdleTime: 60
    packagesToScan: com.jees.test.entity

